trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    pip install -r requirements.txt
  displayName: 'Install Python dependencies'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g sass uglify-js
    sass static/style.scss static/style.css
    uglifyjs static/script.js -o static/script.min.js
  displayName: 'Build assets (SCSS + JS minify)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Twoja-nazwa-subskrypcji'   # <- dodaj w DevOps "Service connection"
    appName: 'Lab-1-Kalkulator'
    package: '$(System.DefaultWorkingDirectory)'
